"""empty message

Revision ID: 7916e79876af
Revises: da2571885562
Create Date: 2016-07-09 17:39:02.275356

"""

# revision identifiers, used by Alembic.
revision = '7916e79876af'
down_revision = 'da2571885562'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=True),
    sa.Column('target_time', sa.Date(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    ### end Alembic commands ###
