"""empty message

Revision ID: da2571885562
Revises: 42b88730b7f7
Create Date: 2016-07-06 16:10:51.643907

"""

# revision identifiers, used by Alembic.
revision = 'da2571885562'
down_revision = '42b88730b7f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
